export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
export const ACCOUNT_SET_AUTHENTICATION = "ACCOUNT_SET_AUTHENTICATION";
export const ACCOUNT_PURGE_AUTHENTICATION = "ACCOUNT_PURGE_AUTHENTICATION";
export const ACCOUNT_CHECK_AUTHENTICATION = "ACCOUNT_CHECH_AUTHENTICATION";
