export const SOCKET_CHAT_SEND = "SOCKET_CHAT_SEND";
export const SOCKET_CHAT_RECENT = "SOCKET_CHAT_RECENT";
export const FETCH_CHATS = "FETCH_CHATS";
export const SET_CHATS = "SET_CHATS";
export const SOCKET_CHAT_ADD_TYPING_ACCOUNT_INDICATOR =
  "SOCKET_CHAT_ADD_TYPING_ACCOUNT_INDICATOR";
export const SOCKET_CHAT_REMOVE_TYPING_ACCOUNT_INDICATOR =
  "SOCKET_CHAT_REMOVE_TYPING_ACCOUNT_INDICATOR";
