export const ROOM_CREATE = "ROOM_CREATE";
export const ROOM_SEARCH = "ROOM_SEARCH";
export const ROOM_GET_INFORMATION = "ROOM_GET_INFORMATION";
export const SOCKET_ROOM_MEMBERS = "SOCKET_ROOM_MEMBERS";
export const ROOM_GET_FEATURED = "ROOM_GET_FEATURED";
export const ROOM_JOIN = "ROOM_JOIN";
export const ROOM_LEAVE = "ROOM_LEAVE";
export const ROOM_DESTROY = "ROOM_DESTROY";
