export const ROOM_CREATE = "ROOM_CREATE";
export const ROOM_SEARCH = "ROOM_SEARCH";
export const ROOM_GET_INFORMATION = "ROOM_GET_INFORMATION";
export const SOCKET_ROOM_MEMBERS = "SOCKET_ROOM_MEMBERS";
export const SOCKET_ROOM_JOINED = "SOCKET_ROOM_JOINED";
export const ROOM_GET_FEATURED = "ROOM_GET_FEATURED";
